/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import classes.Alunos;
import classes.Endereco;
import classes.Menus;
import classes.Professores;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;


/**
 *
 * @author tiago
 */
public class SistemaAcademico extends javax.swing.JFrame {
    String registroProcurado = "";
    
    Endereco endereco = new Endereco();
    Alunos alunos = new Alunos();       
    Professores professores = new Professores();
    
    List listaDisciplinas = new ArrayList();
    HashMap<String,List> cursosEDisciplinas = new HashMap();
    List<Alunos> listaAlunos = new <Alunos>ArrayList();
    List<Professores> listaProfessores = new <Professores>ArrayList();
    /**
     * Creates new form Professores
     */
    public SistemaAcademico() {
        try {
            UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(SistemaAcademico.class.getName()).log(Level.SEVERE, null, ex);
        }       
  
        initComponents();
        
        desativarBotoesCancelarSalvar();//Esses botoes só são ativados quando a função ALTERAR é requisitada. 
        jBAlterarCursoMateria.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCAlunoOuProfessor = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTRegistroAluno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTRegistroProfessor = new javax.swing.JTextField();
        jTCurso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jBAdicionarCursosMaterias = new javax.swing.JButton();
        jBAlterarCursoMateria = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jCEstado = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTCidade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTBairro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTRua = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTNumero = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTComplemento = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTNome = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTDDD = new javax.swing.JTextField();
        jTTelefone = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jCSexo = new javax.swing.JComboBox<>();
        jBCadastrar = new javax.swing.JButton();
        jBAlterar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jBPesquisar = new javax.swing.JButton();
        jBTesteAluno = new javax.swing.JButton();
        jBTesteProfessor = new javax.swing.JButton();
        jBSalvar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Acadêmico");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jCAlunoOuProfessor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Professor", "Aluno" }));
        jCAlunoOuProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCAlunoOuProfessorActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCAlunoOuProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCAlunoOuProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Registro do Aluno:");

        jTRegistroAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTRegistroAlunoActionPerformed(evt);
            }
        });

        jLabel3.setText("Registro do Professor:");

        jTCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCursoActionPerformed(evt);
            }
        });

        jLabel4.setText("Curso:");

        jBAdicionarCursosMaterias.setText("Cursos e Matérias");
        jBAdicionarCursosMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarCursosMateriasActionPerformed(evt);
            }
        });

        jBAlterarCursoMateria.setText("Alterar Cursos e Matérias");
        jBAlterarCursoMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarCursoMateriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTRegistroAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBAdicionarCursosMaterias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBAlterarCursoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTRegistroProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTRegistroAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jTRegistroProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jBAdicionarCursosMaterias)
                    .addComponent(jBAlterarCursoMateria))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Estado:");

        jCEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Acre (AC)", "Alagoas (AL)", "Amapá (AP)", "Amazonas (AM)", "Bahia (BA)", "Ceará (CE)", "Distrito Federal (DF)", "Espírito Santo (ES)", "Goiás (GO)", "Maranhão (MA)", "Mato Grosso (MT)", "Mato Grosso do Sul (MS)", "Minas Gerais (MG)", "Pará (PA)", "Paraíba (PB)", "Paraná (PR)", "Pernambuco (PE)", "Piauí (PI)", "Rio de Janeiro (RJ)", "Rio Grande do Norte (RN)", "Rio Grande do Sul (RS)", "Rondônia (RO)", "Roraima (RR)", "Santa Catarina (SC)", "São Paulo (SP)", "Sergipe (SE)", "Tocantins (TO)", "" }));
        jCEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCEstadoActionPerformed(evt);
            }
        });

        jLabel7.setText("Cidade:");

        jTCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCidadeActionPerformed(evt);
            }
        });

        jLabel8.setText("Bairro:");

        jLabel9.setText("Rua:");

        jLabel10.setText("Número:");

        jTComplemento.setColumns(20);
        jTComplemento.setRows(5);
        jScrollPane1.setViewportView(jTComplemento);

        jLabel11.setText("Complemento:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jCEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jTBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTRua, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                    .addComponent(jTCidade)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jCEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jTRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setText("Nome:");

        jLabel13.setText("DDD:");

        jLabel14.setText("Telefone:");

        jLabel15.setText("Sexo:");

        jCSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Masculino", "Feminino", "Outro" }));
        jCSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCSexoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTDDD, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTTelefone)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jTDDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jCSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBCadastrar.setText("Cadastrar");
        jBCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBCadastrar.setDefaultCapable(false);
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        jBAlterar.setText("Alterar");
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBPesquisar.setText("Pesquisar");
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });

        jBTesteAluno.setText("A");
        jBTesteAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTesteAlunoActionPerformed(evt);
            }
        });

        jBTesteProfessor.setText("P");
        jBTesteProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTesteProfessorActionPerformed(evt);
            }
        });

        jBSalvar.setText("Salvar");
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBTesteAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBTesteProfessor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBCadastrar)
                        .addGap(10, 10, 10)
                        .addComponent(jBAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCadastrar)
                    .addComponent(jBAlterar)
                    .addComponent(jBExcluir)
                    .addComponent(jBPesquisar)
                    .addComponent(jBTesteAluno)
                    .addComponent(jBTesteProfessor)
                    .addComponent(jBSalvar)
                    .addComponent(jBCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    private void jTRegistroAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTRegistroAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTRegistroAlunoActionPerformed

    private void jTCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCursoActionPerformed

    private void jTCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCidadeActionPerformed

    private void jCSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCSexoActionPerformed
        
    }//GEN-LAST:event_jCSexoActionPerformed

    private void jCAlunoOuProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCAlunoOuProfessorActionPerformed
        if(jCAlunoOuProfessor.getSelectedItem().equals("Professor")){
            jTRegistroProfessor.setEnabled(true);
            jBAdicionarCursosMaterias.setEnabled(true);
            jTRegistroAluno.setEnabled(false);
            jTCurso.setEnabled(false);

        }else if (jCAlunoOuProfessor.getSelectedItem().equals("Aluno")){
            jTRegistroAluno.setEnabled(true);
            jTCurso.setEnabled(true);
            jTRegistroProfessor.setEnabled(false);
            jBAdicionarCursosMaterias.setEnabled(false);
        }
    }//GEN-LAST:event_jCAlunoOuProfessorActionPerformed

    private void jCEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCEstadoActionPerformed

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        
        cadastrarEndereco(); 
        
        if(jCAlunoOuProfessor.getSelectedItem().toString().equals("Aluno")){
            cadastrarAluno();
            listaAlunos.add(alunos);    
            JOptionPane.showMessageDialog(null,"Aluno cadastrado com sucesso!");
        }else{
            cadastrarProfessor();
            listaProfessores.add(professores);
            JOptionPane.showMessageDialog(null,"Professor cadastrado com sucesso!");          
        }      
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
     
        String escolha = Menus.escolhaMenuAlunoProfessor();
      
        if(escolha.equals("1")){
            registroProcurado();
            for(Alunos alunos: listaAlunos){          
                if(alunos.getRa().equals(registroProcurado)){
                    alunos.exibirAluno(alunos);
                return;   
                }                    
            }           
            JOptionPane.showMessageDialog(null,"Aluno não encontrado :(");  
        
        }else if(escolha.equals("2")){
            registroProcurado();                               
            for(Professores professores: listaProfessores){          
                if(professores.getRegistro().equals(registroProcurado)){
                    professores.exibirProfessor(professores);
                return;    
                }                     
            }
            JOptionPane.showMessageDialog(null,"Professor não encontrado :("); 
        
        }else{
            JOptionPane.showMessageDialog(null,"Opção Inválida!");
        } 
    }//GEN-LAST:event_jBPesquisarActionPerformed

    private void jBTesteAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTesteAlunoActionPerformed
        testeAluno();
        testeEndereco();
    }//GEN-LAST:event_jBTesteAlunoActionPerformed

    private void jBTesteProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTesteProfessorActionPerformed
        testeProfessor();
        testeEndereco();
    }//GEN-LAST:event_jBTesteProfessorActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
     
        String escolha = Menus.escolhaMenuAlunoProfessor();
        
        if(escolha.equals("1")){
            alunos.removerAluno(listaAlunos,pegarIndiceAluno());      
            
        }else if(escolha.equals("2")){
            professores.removerProfessor(listaProfessores,pegarIndiceProfessor());    
            
        }else{
            JOptionPane.showMessageDialog(null,"Opção Inválida!");
        } 
        
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBAdicionarCursosMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarCursosMateriasActionPerformed
        adicionarCurso();
    }//GEN-LAST:event_jBAdicionarCursosMateriasActionPerformed

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed
    
        String escolha = Menus.escolhaMenuAlunoProfessor();       
        if(escolha.equals("1")){          
            registroProcurado();
            carregarDadosAluno(registroProcurado); 
            desativarBotoesCRUD();
            ativarBotoesCancelarSalvar();
            
        }else if(escolha.equals("2")){
            
        }else{
            JOptionPane.showMessageDialog(null,"Opção Inválida!");
        }    
    }//GEN-LAST:event_jBAlterarActionPerformed

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed
        
        salvarAlterarAluno(registroProcurado);     
        ativarBotoesCRUD();
        desativarBotoesCancelarSalvar();
        
    }//GEN-LAST:event_jBSalvarActionPerformed

    private void jBAlterarCursoMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarCursoMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBAlterarCursoMateriaActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        
        JOptionPane.showMessageDialog(null,"Operação cancelada");
        ativarBotoesCRUD();
        desativarBotoesCancelarSalvar();
        limparCampos();
    }//GEN-LAST:event_jBCancelarActionPerformed
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdicionarCursosMaterias;
    private javax.swing.JButton jBAlterar;
    private javax.swing.JButton jBAlterarCursoMateria;
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JButton jBTesteAluno;
    private javax.swing.JButton jBTesteProfessor;
    private javax.swing.JComboBox<String> jCAlunoOuProfessor;
    private javax.swing.JComboBox<String> jCEstado;
    private javax.swing.JComboBox<String> jCSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTBairro;
    private javax.swing.JTextField jTCidade;
    private javax.swing.JTextArea jTComplemento;
    private javax.swing.JTextField jTCurso;
    private javax.swing.JTextField jTDDD;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTextField jTNumero;
    private javax.swing.JTextField jTRegistroAluno;
    private javax.swing.JTextField jTRegistroProfessor;
    private javax.swing.JTextField jTRua;
    private javax.swing.JTextField jTTelefone;
    // End of variables declaration//GEN-END:variables

    public void cadastrarEndereco(){
        endereco = new Endereco(jTRua.getText(),Integer.parseInt(jTNumero.getText()),
                jCEstado.getSelectedItem().toString(),jTCidade.getText(),
                jTBairro.getText(),jTComplemento.getText());      
    }
    
    public void cadastrarAluno(){      
        alunos = new Alunos(jTRegistroAluno.getText(),jTNome.getText(),
                endereco,jTCurso.getText(),Integer.parseInt(jTTelefone.getText()),
                jCSexo.getSelectedItem().toString());   
        
    }   
    public void cadastrarProfessor(){
        professores = new Professores(jTRegistroProfessor.getText(),jTNome.getText()
                ,endereco,Integer.parseInt(jTTelefone.getText()), 
                jCSexo.getSelectedItem().toString());
        
        professores.setCursosEDisciplinas(cursosEDisciplinas);        
        cursosEDisciplinas = new HashMap();
        listaDisciplinas = new ArrayList();
        
    }   
    
    public void carregarDadosAluno(String raProcurado){       
        for(Alunos alunos: listaAlunos){          
            if(alunos.getRa().equals(raProcurado)){
                JOptionPane.showMessageDialog(null,"Aluno encontrado!"
                        + "\nPreencha o formulário com os novos dados e clique em (Salvar)");
                    jCAlunoOuProfessor.setSelectedIndex(2);
                    jCAlunoOuProfessor.setEnabled(false);                      
                    jTRegistroAluno.setText(alunos.getRa());
                    jTNome.setText(alunos.getNome());
                    jTCurso.setText(alunos.getCurso());
                    jTTelefone.setText(Integer.toString(alunos.getTelefone()));
                    jCSexo.setSelectedItem(alunos.getSexo());
                    jTRua.setText(alunos.getEndereco().getRua());
                    jTNumero.setText(Integer.toString(alunos.getEndereco().getNumero()));
                    jCEstado.setSelectedItem(alunos.getEndereco().getEstado());
                    jTCidade.setText(alunos.getEndereco().getCidade());
                    jTBairro.setText(alunos.getEndereco().getBairro());
                        
                return;   
            }                    
        }
            
        JOptionPane.showMessageDialog(null,"Aluno não encontrado :(");    
       
    }
    
    public void salvarAlterarAluno(String raProcurado){
        for(Alunos alunos: listaAlunos){          
            if(alunos.getRa().equals(raProcurado)){
                alunos.setRa(jTRegistroAluno.getText());
                alunos.setNome(jTNome.getText());
                alunos.setCurso(jTCurso.getText());
                alunos.setTelefone(Integer.parseInt(jTTelefone.getText()));
                alunos.setSexo(jCSexo.getSelectedItem().toString());
                
                endereco.setRua(jTRua.getText());
                endereco.setNumero(Integer.parseInt(jTNumero.getText()));
                endereco.setEstado(jCEstado.getSelectedItem().toString());
                endereco.setCidade(jTCidade.getText());
                endereco.setBairro(jTBairro.getText());
                
                alunos.setEndereco(endereco);                       
                  
            }                    
        }
        
        JOptionPane.showMessageDialog(null,"Dados salvos com sucesso");
    }
    
    
       
    public int pegarIndiceAluno(){ 
        registroProcurado();
            for(Alunos alunos: listaAlunos){                      
                if(alunos.getRa().equals(registroProcurado)){
                    return listaAlunos.indexOf(alunos);                  
                }                                                       
            }
            JOptionPane.showMessageDialog(null,"Aluno não encontrado :(");
        return -1;
    }
    
    public int pegarIndiceProfessor(){   
        registroProcurado();    
            for(Professores professores: listaProfessores){                      
                if(professores.getRegistro().equals(registroProcurado)){
                    return listaProfessores.indexOf(professores);                  
                }                    
            }           
            JOptionPane.showMessageDialog(null,"Professor não encontrado :(");           
        
        return -1;
    }
    
    public void registroProcurado(){
        registroProcurado = JOptionPane.showInputDialog("Digite o número de registro");
    }
    
    public void adicionarCurso(){
        String curso, disciplina = "";        
        listaDisciplinas = new ArrayList();    
        curso = JOptionPane.showInputDialog("Digite o curso");
        
        do{
            disciplina = JOptionPane.showInputDialog("Digite a matéria "
                    + "\nOu digite (3) para sair");            
            if(!disciplina.equals("3")){               
                listaDisciplinas.add(disciplina);
            }  
            
        }while(!disciplina.equals("3"));       
        cursosEDisciplinas.put(curso, listaDisciplinas);
    }
    
    public void limparCampos(){
        jCAlunoOuProfessor.setSelectedIndex(0);
        jCAlunoOuProfessor.setEnabled(true);                      
        jTRegistroAluno.setText("");
        jTNome.setText("");
        jTCurso.setText("");
        jTTelefone.setText("");
        jCSexo.setSelectedIndex(0);
        jTRua.setText("");
        jTNumero.setText("");
        jCEstado.setSelectedIndex(0);
        jTCidade.setText("");
        jTBairro.setText("");
    }
       
    public void desativarBotoesCancelarSalvar(){
        jBCancelar.setVisible(false);
        jBSalvar.setVisible(false);
    }
    
    public void ativarBotoesCancelarSalvar(){
        jBCancelar.setVisible(true);
        jBSalvar.setVisible(true);
    }
    
    public void desativarBotoesCRUD(){              
        jBCadastrar.setVisible(false);
        jBAlterar.setVisible(false);
        jBPesquisar.setVisible(false);
        jBExcluir.setVisible(false);    
    }
    
    public void ativarBotoesCRUD(){
        jBCadastrar.setVisible(true);
        jBAlterar.setVisible(true);
        jBPesquisar.setVisible(true);
        jBExcluir.setVisible(true); 
    }
    
    
    //Preenche os campos do formulário com esses dados
    public void testeAluno(){
        jCAlunoOuProfessor.setSelectedIndex(2);
        jTRegistroAluno.setText("1234");
        jTNome.setText("Tiago");
        jTCurso.setText("ADS");
        jTTelefone.setText("47557656");
        jCSexo.setSelectedIndex(1);                      
    }
    public void testeProfessor(){
        jCAlunoOuProfessor.setSelectedIndex(1);
        jTRegistroProfessor.setText("4321");
        jTNome.setText("Tiago");       
        jTTelefone.setText("47557656");
        jCSexo.setSelectedIndex(1);
    }
    public void testeEndereco(){ 
        jTRua.setText("Adonias Filho");
        jTNumero.setText("101");
        jCEstado.setSelectedIndex(1);
        jTCidade.setText("Itaquaquecetuba");
        jTBairro.setText("Jardim Moraes");      
    }
    
}